rasterizer:
  command: phantomjs
  port: 3001
  path: '/tmp/'
  viewport: '1024x600'
  cache:
    active: false
    path: '/tmp/cache/'
    cleanup: true
    cleanupInterval: 5000
    maxItems: 100
    maxAge: 5000
server:
  port: 3000
